// import 'function.name-polyfill';
import 'babel-polyfill';
import 'dom4';
import 'whatwg-fetch';
import './shim.classlist';
import './shim.hidden';
import './shim.click';
import './shim.head';
import './shim.selectedoptions';
import './shim.details';
